### ISSUE TITLE
Feature: Get rid of popup when selecting text

### ISSUE THREAD

**Issue by lll000111** [thebaer/MMRA#21]
Source: https://news.ycombinator.com/item?id=16516676

mayneack wrote:

> As a serial selecter, I wish it would get rid of the popup when you select text. 

![screenshot](https://i.imgur.com/G5x0U9P.png)

**Comment by davidgomes** [comment]
```
.highlightMenu {
display: none;
}
```

Does it for me.

**Comment by lll000111** [comment]
@davidgomes Everything this extension does can be achieved in another way. That's not the point.

**Comment by davidgomes** [comment]
Yes, I realize that — I'm just trying to help a future implementer of this feature. I apologize as my wording was not really clear.

**Comment by thebaer** [comment]
Thanks for opening the issue -- going to move the discussion to #20
