### ISSUE TITLE
Hide sign up/sign in "Pardon the interruption" popup

### ISSUE THREAD

**Issue by jorgegonzalez** [thebaer/MMRA#24]
![image](https://user-images.githubusercontent.com/12901172/38428562-0eef334e-398a-11e8-8684-250cfbf4eb1d.png)

Not sure if this has been reported already.

**Comment by panckreous** [comment]
Ha, this is one project where duplicate issues are more likely valid new issues than not. Matt cures one malady but in no time a newer, stronger, grosser variation breaks out.

**Comment by jorgegonzalez** [comment]
I really hate what Medium has become. I'll try and send a PR this weekend to fix this.

**Comment by thebaer** [comment]
Thanks @jorgegonzalez, that would be awesome!

**Comment by jorgegonzalez** [comment]
I've been trying to fix this but I can't reliably trigger the overlay 🤔

**Comment by thebaer** [comment]
@jorgegonzalez I was just able to get it to happen twice by opening an incognito window, going to Medium.com and clicking on four different articles... Maybe that'll work?

**Comment by jorgegonzalez** [comment]
@thebaer Just opened a PR.

**Comment by thebaer** [comment]
@jorgegonzalez looks great! Left a comment about some potential side effects -- will merge as soon as they're addressed.
