### ISSUE TITLE
Unnecessary browser_action in manifest.json

### ISSUE THREAD

**Issue by ris58h** [thebaer/MMRA#32]
`browser_action` section with `default_icon` adds an extensions icon to browser's top bar (true for Firefox; Chrome adds the icon even there is no `browser_action` specified).
As I can see there is no any action this extension performs when user clicks the icon. So in Firefox I just have unnecessary icon in the top bar. Could you remove it?

**Comment by thebaer** [comment]
Great point! Definitely don't need it in there. I'm happy to merge a pull request if you submit one -- otherwise I'll get to this when I have a chance.
