### ISSUE TITLE
Firefox version, please pretty please

### ISSUE THREAD

**Issue by mvasilkov** [thebaer/MMRA#4]
Hi, and thank you for this literally must-have browser extension, awesome work!

Are there any plans to do a Firefox port?

**Comment by thebaer** [comment]
Thanks! There weren't plans, but I'll make the few other pending fixes (#1, #5) and then look into what it'd take to port over to Firefox

**Comment by bfred-it** [comment]
![good-news-everyone](https://user-images.githubusercontent.com/1402241/29860080-f6438a7c-8d8e-11e7-921e-3cb6a442e88b.jpg)

It's already compatible. You only need to submit it to Mozilla Addons

<img width="981" alt="MMRA on Firefox" src="https://user-images.githubusercontent.com/1402241/29860071-ed5c7fa4-8d8e-11e7-836b-2521d291e1e5.png">

**Comment by thebaer** [comment]
🙌 sweet! Waiting on approval now -- will be installable [here](https://addons.mozilla.org/en-US/firefox/addon/make-medium-readable-again/) when it's ready.

**Comment by thebaer** [comment]
This was [just approved](https://addons.mozilla.org/addon/make-medium-readable-again/)! @ivanatpr @mvasilkov @hg8 @panckreous
