### ISSUE TITLE
Not Working on External Sites

### ISSUE THREAD

**Issue by jimbo1qaz** [thebaer/MMRA#40]
The extension doesn't seem to work on https://android.jlelse.eu/some-asynchronous-options-on-android-cb6b0c156c98 (which is actually a Medium page).

Firefox 64.0a1 (2018-09-13) (64-bit)
Addon 1.5.1

**Comment by thebaer** [comment]
As mentioned in #41, I'm not able to replicate the issue on that URL -- everything seems to work fine. Let me know if you find another site it doesn't work on though and I'll reopen this.
