### ISSUE TITLE
Disable dynamic loading of images?

### ISSUE THREAD

**Issue by nick-s-b** [thebaer/MMRA#5]
Wow, what an excellent extension! Thank you so much @thebaer ! I have a request but I'm not sure if it's possible. One of the biggest annoyances is dynamic loading of images on Medium. When  I open a page, none of the images below the fold are actually loaded which means if I disconnect from the network (during a commute), I won't see any of the images below. Would it be possible to load all the images when the page loads? Thanks!

**Comment by thebaer** [comment]
Yep, this was pretty straightforward to add! I tested it out on [this post](https://medium.com/@abear/a-post-with-many-photos-3cbcfffea713) and it seems to work well.

You'll see it as an option to _Disable lazy image loading_ in the next version, ideally going out tonight.

**Comment by nick-s-b** [comment]
Thanks so much @thebaer !!!
