### ISSUE TITLE
Option to disable default features

### ISSUE THREAD

**Issue by Stevoisiak** [thebaer/MMRA#54]
The options menu for MMRA on Firefox has three default features: Unstick navigation bar, hide updates bar, and smaller header images. These options cannot be disabled without uninstalling the addon.

It would be nice to have an option to individually override these default settings.

![Default features](https://user-images.githubusercontent.com/1330770/61147907-92c11100-a4ab-11e9-836f-f1e88fb63e37.png)

**Comment by thebaer** [comment]
Thanks for the input. Those "options" simply explain what the extension does, and I think they're pretty core to everything. If anyone wants to disable them, I think that'd be best handled by forking this into a completely new extension.
