### ISSUE TITLE
Too broad permissions

### ISSUE THREAD

**Issue by alexanderkjeldaas** [thebaer/MMRA#55]
Why is this extension asking for permission to access all websites?

This should either be prominently documented in the description or removed.

**Comment by thebaer** [comment]
As mentioned here, there are sites powered by Medium that aren't hosted at `medium.com`: https://github.com/thebaer/MMRA/blob/0e53dcb8a102843d4fad038c16a119a0fd0ac9ee/content.js#L85-L87


This is the correct solution: #15. Closing since it's a duplicate.
