### ISSUE TITLE
Can it work with custom domains?

### ISSUE THREAD

**Issue by moltar** [thebaer/MMRA#58]
E.g. https://itnext.io/ is on Medium, which allowed custom domains at the start, and I don't think this extension has any effect on that. Thanks.

**Comment by thebaer** [comment]
Hey, thanks for the report! It does work on custom domains (see #15), however the extension needs some work in general to keep up with Medium's changes.

**Comment by haykerman** [comment]
I've created a new extension inspired by MMRA which works on custom domains.

Here you go: [Medium Focus](https://chrome.google.com/webstore/detail/medium-focus/dflmdnklfhnladdmbgnplengjaiblhdn)
